import { notFound } from "next/navigation";
import { getCurrentUser } from "@/lib/auth";
import { getAccessibleSession } from "@/lib/access";
import{ prisma }from "@/lib/prisma";
import StatusBadge from "@/components/StatusBadge";
import StartSessionButton from "@/components/StartSessionButton";
import FeedbackFeed from "@/components/FeedbackFeed";
import FeedbackForm from "@/components/FeedbackForm";
import ReportPanel from "@/components/ReportPanel";

export default async function SessionDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const user = await getCurrentUser();
  if (!user)
    return (
    <div className="space-y-10">
            <div className="card">
              <p className="text-sm text-muted">
                Return to the <a href="/login" className="text-primary">login page</a> to view this session.
              </p>
            </div>
      </div>
    ); // layout redirects

  const access = await getAccessibleSession(id, user);
  if (!access) 
    return (
    <div className="space-y-10">
            <div className="card">
              <p className="text-sm text-muted">
                You do not have access to this session, or it does not exist. Please check the link and try again.
              </p>
            </div>
      </div>
    );

  const { session, isOwner, isAssignedPlaytester } = access;

  const [feedback, reports] = await Promise.all([
    prisma.feedback.findMany({
      where: { sessionId: session.id },
      include: { author: { select: { name: true } } },
      orderBy: { createdAt: "desc" },
    }),
    prisma.report.findMany({
      where: { sessionId: session.id },
      orderBy: { createdAt: "desc" },
    }),
  ]);

  const feedbackForFeed = feedback.map((f) => ({
    ...f,
    createdAt: f.createdAt.toISOString(),
  }));
  const reportsForPanel = reports.map((r) => ({
    ...r,
    createdAt: r.createdAt.toISOString(),
  }));

  return (
    <div className="space-y-10">
      <div>
        <p className="label">// session</p>
        <div className="mt-2 flex flex-wrap items-center justify-between gap-4">
          <div>
            <h1 className="font-display text-2xl font-semibold text-ink">
              {session.game.title}
            </h1>
            <p className="mt-1 font-mono text-xs text-faint">{session.game.studio.name}</p>
          </div>
          <div className="flex items-center gap-3">
            <StatusBadge status={session.status} />
            {isOwner && session.status === "scheduled" ? (
              <StartSessionButton sessionId={session.id} />
            ) : null}
          </div>
        </div>
      </div>

      <div className="grid gap-8 lg:grid-cols-2">
        {feedbackForFeed.length > 0 ? (
          <div className="space-y-6">
            <p className="label">live feedback</p>
            {isAssignedPlaytester && session.status === "live" ? (
              <FeedbackForm sessionId={session.id} />
            ) : null}
            <FeedbackFeed sessionId={session.id} initialFeedback={feedbackForFeed} />
          </div>
        ) : (
          <div className="card">
            <p className="text-sm text-muted">
              No feedback has been submitted for this session yet.
            </p>
          </div>
        )}
        

        {reportsForPanel.length > 0 ? (
          <div>
          {isOwner ? (
            <ReportPanel sessionId={session.id} initialReports={reportsForPanel} />
          ) : (
            <div className="card">
              <p className="text-sm text-muted">
                AI QA summaries are generated by the studio once enough feedback is in.
              </p>
            </div>
          )}
        </div>
        ) : <div className="card">
          <p className="text-sm text-muted">
            No reports available for this session.
          </p>
        </div>}
      </div>
    </div>
  );
}
